# Generated by Django 4.0.3 on 2022-03-30 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartFinance', '0002_groupmembers'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensegroup',
            name='group_member_name',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
